/* ELIF OS V2 — unified state + progress engine */
(() => {
  const KEY='elif-os-v2-state'; const $=(s,r=document)=>r.querySelector(s); const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const id=()=>crypto.randomUUID(); const today=()=>new Date().toISOString().slice(0,10); const money=n=>'₺'+Number(n||0).toLocaleString('tr-TR',{maximumFractionDigits:0});
  const blank={tasks:[],habits:[],habitLog:{},studyMinutes:0,water:{},sleep:{},wallet:{balance:0,transactions:[]},goals:[],projects:[],journal:[],meals:{},notes:[],brain:'',focusMinutes:0};
  const seed=()=>({ ...blank,
    tasks:[['Review pharmacy notes','high'],['20 min Korean practice','medium'],["Log today's spending",'low']].map(([title,priority])=>({id:id(),title,priority,date:today(),done:false,projectId:null,goalId:null})),
    habits:['Korean','Study','Movement','Water','Sleep','Read'].map(name=>({id:id(),name})),
    goals:[['Become conversational in Korean','Korean',38],['Master core pharmacy subjects','Academics',54],['Build a stronger body','Body',44],['Build saving + investing system','Finance',27]].map(([title,area,progress])=>({id:id(),title,area,progress})),
    projects:[['Korean speaking','Korean'],['Semester pharmacy prep','Academics'],['Personal finance system','Finance']].map(([name,area])=>({id:id(),name,area})),
    meals:{[today()]:'Chicken bowl'}, notes:[], journal:[], wallet:{balance:0,transactions:[]}
  });
  let state; try{state=JSON.parse(localStorage.getItem(KEY))||seed()}catch{state=seed()}
  const save=()=>{localStorage.setItem(KEY,JSON.stringify(state)); render();};
  const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1600)};
  const taskDone=()=>state.tasks.filter(t=>t.date===today()&&t.done).length;
  const taskTotal=()=>state.tasks.filter(t=>t.date===today()).length;
  const habitDone=()=>state.habits.filter(h=>state.habitLog[h.id]?.[today()]).length;
  const habitTotal=()=>state.habits.length;
  const waterToday=()=>Number(state.water[today()]||0);
  const studyToday=()=>Number(state.studyLog?.[today()]||0);
  const dailyProgress=()=>{const parts=[taskTotal()?taskDone()/taskTotal():1,habitTotal()?habitDone()/habitTotal():1,Math.min(studyToday()/120,1),Math.min(waterToday()/2,1),state.sleep[today()]?Math.min(Number(state.sleep[today()])/8,1):0];return Math.round(parts.reduce((a,b)=>a+b,0)/parts.length*100)};
  const score=()=>Math.round(dailyProgress()*0.7 + Math.min(state.goals.reduce((a,g)=>a+Number(g.progress||0),0)/(Math.max(state.goals.length,1)*100)*100,100)*0.2 + Math.min(state.projects.filter(p=>p.progress>=100).length/Math.max(state.projects.length,1),1)*10);
  const progress=(v)=>`<div class="progress"><i style="width:${Math.max(0,Math.min(100,v))}%"></i></div>`;
  function shell(){
    $('#app').innerHTML=`<div class="shell"><aside><div class="brand">ELIF OS <span>//</span><small>v2.0 · personal operating system</small></div><nav>${[['home','⌂','Home'],['tasks','✓','Tasks'],['goals','◉','Goals'],['projects','◇','Projects'],['habits','🔥','Habits'],['study','📓','Study'],['glow','🧘🏻‍♀️','Glow Up'],['body','🩰','Body'],['wallet','💳','Wallet'],['meal','🍱','Meal'],['journal','🖊️','Journal']].map(([p,i,n])=>`<button data-page="${p}">${i}<span>${n}</span></button>`).join('')}</nav><div class="side-note">discipline now,<br>freedom later. ♡</div></aside><main><header><button class="menu" data-menu>☰</button><div>ELIF OS <b>/</b> <span id="crumb">Home</span></div><div class="header-actions"><button data-add>＋</button><button data-search>⌕</button><button data-reset>↻</button></div></header><div id="view"></div></main></div><div id="modal" class="modal"></div>`;
    document.addEventListener('click',click); document.addEventListener('change',change); document.addEventListener('submit',submit); document.addEventListener('input',handleInput); navigate('home');
  }
  const card=(title,value,sub,bar)=>`<div class="metric"><span>${title}</span><strong>${value}</strong><small>${sub}</small>${bar!==undefined?progress(bar):''}</div>`;
  function home(){const p=dailyProgress(); return `<section><div class="hero"><img src="elif-os-banner.png"><div><span>PERSONAL OPERATING SYSTEM</span><h1>it's going to be okay.</h1><p>Today is built from what you actually do.</p></div></div><div class="head"><div><span class="eyebrow">TODAY</span><h1>my life ✧</h1><p>${new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date())}</p></div><button class="primary" data-add>＋ new</button></div><div class="metrics">${card('Tasks',`${taskDone()} / ${taskTotal()}`,'completed today',taskTotal()?taskDone()/taskTotal()*100:0)}${card('Habits',`${habitDone()} / ${habitTotal()}`,'completed today',habitTotal()?habitDone()/habitTotal()*100:0)}${card('Study',`${studyToday()}m`,'logged today',Math.min(studyToday()/120*100,100))}${card('Water',`${waterToday().toFixed(2)} L`,'of 2.0 L',waterToday()/2*100)}${card('ELIF SCORE',score(),'live system score',score())}</div><div class="grid2"><div class="panel"><div class="panel-title">Today's Focus <span>${p}%</span></div>${progress(p)}<div id="todayList">${state.tasks.filter(t=>t.date===today()).map(t=>`<label class="check"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span>${esc(t.title)}</span></label>`).join('')||'<p class="muted">No tasks yet.</p>'}</div></div><div class="panel"><div class="panel-title">Quick actions</div><div class="quick"><button data-add-task>＋ Task</button><button data-add-habit>🔥 Habit</button><button data-study-add>＋ Study</button><button data-water-add>＋ Water</button><button data-wallet-add>＋ Wallet</button><button data-journal-add>＋ Journal</button></div></div></div><div class="cards">${[['study','study.jpeg','Study',`${studyToday()} min`],['body','body.jpeg','Body',`${waterToday().toFixed(1)} L water`],['goals','body.jpeg','Goals',`${Math.round(state.goals.reduce((a,g)=>a+g.progress,0)/Math.max(state.goals.length,1))}% avg`],['wallet','money.jpeg','Wallet',money(state.wallet.balance)],['journal','hobbies.jpeg','Journal',`${state.journal.length} entries`],['meal','hobbies.jpeg','Meal',state.meals[today()]||'Plan today']].map(([p,img,n,s])=>`<button class="visual" data-page="${p}"><img src="${img}"><div><span>${n}</span><b>${s}</b></div></button>`).join('')}</div></section>`}
  function tasks(){return page('TASKS','Real tasks feed the dashboard, projects, goals and score.',`<div class="toolbar"><button class="primary" data-add-task>＋ new task</button></div><div class="list">${state.tasks.map(t=>`<div class="row ${t.done?'done':''}"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><div><b>${esc(t.title)}</b><small>${t.date} · ${t.priority}</small></div><button data-delete-task="${t.id}">×</button></div>`).join('')||'<p class="muted">No tasks.</p>'}</div>`) }
  function goals(){return page('GOALS','Goals are measured outcomes. Progress is editable and visible everywhere.',`<div class="cards">${state.goals.map(g=>`<div class="panel"><span class="eyebrow">${esc(g.area)}</span><h3>${esc(g.title)}</h3><div class="goal-line"><b>${g.progress}%</b><input type="range" min="0" max="100" value="${g.progress}" data-goal="${g.id}"></div>${progress(g.progress)}</div>`).join('')}</div><button class="primary" data-add-goal>＋ goal</button>`) }
  function projects(){return page('PROJECTS','Projects connect goals to execution.',`<div class="cards">${state.projects.map(p=>{const linked=state.tasks.filter(t=>t.projectId===p.id), done=linked.filter(t=>t.done).length, pct=linked.length?Math.round(done/linked.length*100):Number(p.progress||0);return `<div class="panel"><span class="eyebrow">${esc(p.area)}</span><h3>${esc(p.name)}</h3><strong>${pct}%</strong>${progress(pct)}<small>${done}/${linked.length} linked tasks</small><button data-add-task-project="${p.id}">＋ task</button></div>`}).join('')}</div><button class="primary" data-add-project>＋ project</button>`) }
  function habits(){return page('HABITS','Every check-in updates consistency, daily progress and ELIF SCORE.',`<div class="cards">${state.habits.map(h=>{const on=!!state.habitLog[h.id]?.[today()];return `<button class="habit ${on?'on':''}" data-habit="${h.id}"><strong>${on?'✓':'○'}</strong><span>${esc(h.name)}</span><small>${on?'done today':'tap to complete'}</small></button>`}).join('')}</div><button class="primary" data-add-habit>＋ habit</button>`) }
  function study(){return page('STUDY','Study sessions become real minutes in Today, progress and score.',`<div class="study-focus panel"><span class="eyebrow">POMODORO</span><strong id="timer">25:00</strong><div><button class="primary" data-timer>start</button><button data-timer-reset>reset</button></div><p>Completed sessions today: ${studyToday()} min</p></div><div class="panel"><div class="panel-title">Study log</div><div class="quick"><button data-study-min="25">＋25m</button><button data-study-min="50">＋50m</button><button data-study-min="90">＋90m</button></div></div>`) }
  function glow(){const w=waterToday();return page('GLOW UP','Wellness data feeds Body and the Home dashboard.',`<div class="cards"><div class="panel"><span>WATER</span><h2>${w.toFixed(2)} L / 2.0 L</h2>${progress(w/2*100)}<div class="quick"><button data-water="0.25">+0.25L</button><button data-water="0.5">+0.5L</button><button data-water="0.75">+0.75L</button></div></div><div class="panel"><span>SLEEP</span><h2>${state.sleep[today()]||0}h / 8h</h2>${progress((state.sleep[today()]||0)/8*100)}<button data-sleep>log sleep</button></div></div>`) }
  function body(){return page('BODY','Recovery, water and movement live together.',`<div class="cards"><div class="panel"><span>WATER</span><h2>${waterToday().toFixed(2)} L</h2>${progress(waterToday()/2*100)}<button data-water="0.5">＋ 0.5 L</button></div><div class="panel"><span>SLEEP</span><h2>${state.sleep[today()]||0}h</h2>${progress((state.sleep[today()]||0)/8*100)}<button data-sleep>log sleep</button></div></div>`) }
  function wallet(){const spent=state.wallet.transactions.filter(x=>x.amount<0&&x.date===today()).reduce((a,x)=>a+x.amount,0);return page('WALLET','Every transaction updates your live balance.',`<div class="metrics">${card('Balance',money(state.wallet.balance),'current',100)}${card('Today spent',money(Math.abs(spent)),'outgoing',Math.min(Math.abs(spent)/750*100,100))}</div><button class="primary" data-wallet-add>＋ transaction</button><div class="list">${state.wallet.transactions.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><small>${x.date}</small></div><strong>${money(x.amount)}</strong></div>`).join('')||'<p class="muted">No transactions.</p>'}</div>`) }
  function meal(){return page('MEAL','Your daily meal choice is part of the same state.',`<div class="panel"><h2>Today</h2><input id="mealInput" value="${esc(state.meals[today()]||'')}" placeholder="what are we eating?"><button data-save-meal>save meal</button></div>`) }
  function journal(){return page('JOURNAL','Notes and reflections stay in your OS.',`<div class="panel"><textarea id="journalInput" placeholder="write today..."></textarea><button class="primary" data-save-journal>save entry</button></div><div class="list">${state.journal.map(j=>`<div class="row"><div><b>${esc(j.date)}</b><p>${esc(j.text)}</p></div></div>`).join('')}</div>`) }
  function page(title,desc,content){return `<section><div class="head"><div><span class="eyebrow">ELIF OS</span><h1>${title}</h1><p>${desc}</p></div></div>${content}</section>`}
  function navigate(p){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#crumb').textContent=p[0].toUpperCase()+p.slice(1);$('#view').innerHTML=p==='home'?home():p==='tasks'?tasks():p==='goals'?goals():p==='projects'?projects():p==='habits'?habits():p==='study'?study():p==='glow'?glow():p==='body'?body():p==='wallet'?wallet():p==='meal'?meal():journal();}
  function modal(title,body){$('#modal').innerHTML=`<div class="modal-box"><button class="close" data-close>×</button><span class="eyebrow">ELIF OS</span><h2>${title}</h2>${body}</div>`;$('#modal').classList.add('open')}
  const fieldInput=(name,type='text',value='')=>`<label>${name}<input name="${name}" type="${type}" value="${esc(value)}"></label>`;
  function addTask(projectId=null){modal('New task',`<form data-form="task">${fieldInput('title')}${fieldInput('date','date',today())}<label>priority<select name="priority"><option>low</option><option selected>medium</option><option>high</option></select></label><input type="hidden" name="projectId" value="${projectId||''}"><button class="primary">save</button></form>`)}
  function click(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.page){navigate(b.dataset.page);return}if(b.dataset.close){$('#modal').classList.remove('open');return}if(b.dataset.add||b.dataset.addTask){addTask();return}if(b.dataset.addTaskProject){addTask(b.dataset.addTaskProject);return}if(b.dataset.addHabit){modal('New habit',`<form data-form="habit">${fieldInput('name')}<button class="primary">save</button></form>`);return}if(b.dataset.addGoal){modal('New goal',`<form data-form="goal">${fieldInput('title')}${fieldInput('area')}<button class="primary">save</button></form>`);return}if(b.dataset.addProject){modal('New project',`<form data-form="project">${fieldInput('name')}${fieldInput('area')}<button class="primary">save</button></form>`);return}if(b.dataset.deleteTask){state.tasks=state.tasks.filter(t=>t.id!==b.dataset.deleteTask);save();toast('Task deleted');return}if(b.dataset.habit){const h=state.habits.find(x=>x.id===b.dataset.habit);state.habitLog[h.id]??={};state.habitLog[h.id][today()]=!state.habitLog[h.id][today()];save();toast(state.habitLog[h.id][today()]?'Habit completed':'Habit unchecked');return}if(b.dataset.water){state.water[today()]=waterToday()+Number(b.dataset.water);save();toast('Water logged');return}if(b.dataset.waterAdd){state.water[today()]=waterToday()+0.25;save();toast('Water logged');return}if(b.dataset.studyMin){state.studyLog??={};state.studyLog[today()]=(state.studyLog[today()]||0)+Number(b.dataset.studyMin);state.studyMinutes=(state.studyMinutes||0)+Number(b.dataset.studyMin);save();toast('Study logged');return}if(b.dataset.studyAdd){state.studyLog??={};state.studyLog[today()]=(state.studyLog[today()]||0)+25;save();toast('25m study logged');return}if(b.dataset.walletAdd){modal('New transaction',`<form data-form="wallet">${fieldInput('name')}<label>amount<input name="amount" type="number" step="1"></label><button class="primary">save</button></form>`);return}if(b.dataset.journalAdd){navigate('journal');return}if(b.dataset.saveMeal){state.meals[today()]=$('#mealInput').value;save();toast('Meal saved');return}if(b.dataset.saveJournal){const text=$('#journalInput').value.trim();if(text){state.journal.unshift({id:id(),date:today(),text});save();toast('Journal saved')}}if(b.dataset.sleep){modal('Log sleep',`<form data-form="sleep">${fieldInput('hours','number',8)}<button class="primary">save</button></form>`);return}if(b.dataset.timer){startTimer(b);return}if(b.dataset.timerReset){clearInterval(window.__timer);window.__seconds=1500;const x=$('#timer');if(x)x.textContent='25:00';return}if(b.dataset.reset){localStorage.removeItem(KEY);state=seed();save();toast('Fresh ELIF OS state');}}
  function change(e){if(e.target.dataset.task){const t=state.tasks.find(x=>x.id===e.target.dataset.task);if(t){t.done=e.target.checked;save();toast(t.done?'Task completed':'Task reopened')}}if(e.target.dataset.goal){const g=state.goals.find(x=>x.id===e.target.dataset.goal);g.progress=Number(e.target.value);save();}}
  function submit(e){const f=e.target;if(!f.dataset.form)return;e.preventDefault();const d=Object.fromEntries(new FormData(f));if(f.dataset.form==='task')state.tasks.push({id:id(),title:d.title,date:d.date,priority:d.priority,done:false,projectId:d.projectId||null,goalId:null});if(f.dataset.form==='habit')state.habits.push({id:id(),name:d.name});if(f.dataset.form==='goal')state.goals.push({id:id(),title:d.title,area:d.area,progress:0});if(f.dataset.form==='project')state.projects.push({id:id(),name:d.name,area:d.area});if(f.dataset.form==='wallet'){const amount=Number(d.amount);state.wallet.balance+=amount;state.wallet.transactions.unshift({id:id(),name:d.name,amount,date:today()})}if(f.dataset.form==='sleep')state.sleep[today()]=Number(d.hours);save();$('#modal').classList.remove('open');toast('Saved');}
  function handleInput(e){if(e.target.id==='mealInput')return}
  function startTimer(btn){clearInterval(window.__timer);window.__seconds=window.__seconds||1500;btn.textContent='running';window.__timer=setInterval(()=>{window.__seconds--;const x=$('#timer');if(x)x.textContent=`${String(Math.floor(window.__seconds/60)).padStart(2,'0')}:${String(window.__seconds%60).padStart(2,'0')}`;if(window.__seconds<=0){clearInterval(window.__timer);state.studyLog??={};state.studyLog[today()]=(state.studyLog[today()]||0)+25;state.studyMinutes=(state.studyMinutes||0)+25;save();toast('Focus session complete')}} ,1000)}
  window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){state=JSON.parse(e.newValue);render()}});
  function render(){const active=document.querySelector('nav button.active')?.dataset.page||'home';navigate(active)}
  shell();
})();
