/* ELIF OS v1.3 — local-first personal operating system */
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const KEY = 'elif-os-v14';
const SYNC_KEY = 'elif-os-sync-v1';
const SESSION_KEY = 'elif-os-session-v1';
const todayKey = () => { const d=new Date(); return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10); };
const addDays = (d,n) => { const x=new Date(d+'T12:00:00'); x.setDate(x.getDate()+n); return x.toISOString().slice(0,10); };
const fmtDate = d => new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
const uid = () => crypto?.randomUUID?.() || Math.random().toString(36).slice(2)+Date.now().toString(36);
const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = n => '₺'+Number(n||0).toLocaleString('tr-TR',{maximumFractionDigits:0});

const seed = {
 tasks:[
  {id:uid(),title:'review pharmacy notes',date:todayKey(),priority:'high',done:false,projectId:'',goalId:'',repeat:'none',subtasks:[],created:Date.now()},
  {id:uid(),title:'20 min Korean practice',date:todayKey(),priority:'medium',done:false,projectId:'',goalId:'',repeat:'daily',subtasks:[],created:Date.now()},
  {id:uid(),title:"log today's spending",date:todayKey(),priority:'low',done:false,projectId:'',goalId:'',repeat:'none',subtasks:[],created:Date.now()},
  {id:uid(),title:'workout',date:addDays(todayKey(),1),priority:'medium',done:false,projectId:'',goalId:'',repeat:'weekly',subtasks:[],created:Date.now()},
  {id:uid(),title:'read 30 pages',date:addDays(todayKey(),2),priority:'low',done:false,projectId:'',goalId:'',repeat:'none',subtasks:[],created:Date.now()}
 ],
 habits:[
  {id:uid(),name:'Korean',icon:'한',frequency:'daily',target:1,days:{}},
  {id:uid(),name:'Study',icon:'✎',frequency:'daily',target:1,days:{}},
  {id:uid(),name:'Movement',icon:'⌁',frequency:'3x week',target:3,days:{}},
  {id:uid(),name:'Water goal',icon:'◌',frequency:'daily',target:1,days:{}},
  {id:uid(),name:'Sleep routine',icon:'☾',frequency:'daily',target:1,days:{}},
  {id:uid(),name:'Read',icon:'▤',frequency:'daily',target:1,days:{}}
 ],
 studyTasks:[
  {id:uid(),title:'pharmacy mechanisms',subject:'Pharmacology',done:false},
  {id:uid(),title:'bio practice test',subject:'Biochemistry',done:false},
  {id:uid(),title:'Korean speaking',subject:'Korean',done:false}
 ],
 studyMinutes:0, studyLog:{},
 subjects:[{id:uid(),name:'Pharmacology',progress:42},{id:uid(),name:'Biochemistry',progress:64},{id:uid(),name:'Korean',progress:31},{id:uid(),name:'Anatomy',progress:55},{id:uid(),name:'Finance',progress:18}],
 notes:[{id:uid(),title:'Autonomic nervous system',subject:'Pharmacology',due:todayKey(),push:'day 1'},{id:uid(),title:'Korean connectors',subject:'Korean',due:addDays(todayKey(),2),push:'day 3'}],
 studyBlocks:[],
 routines:[
  {id:uid(),name:'Supplements',icon:'＋',frequency:'weekly',target:1},
  {id:uid(),name:'Digital detox',icon:'⌁',frequency:'daily',target:1},
  {id:uid(),name:'Hydration',icon:'◌',frequency:'daily',target:1},
  {id:uid(),name:'Skin care',icon:'♡',frequency:'daily',target:1},
  {id:uid(),name:'Mindfulness',icon:'☁',frequency:'3x week',target:3},
  {id:uid(),name:'Stretching',icon:'⌁',frequency:'daily',target:1}
 ],
 routineLog:{}, glowLogs:[], waterLog:{}, waterGoal:2, sleepLogs:{}, sleepGoal:8,
 entries:[{id:uid(),name:'coffee',category:'food',amount:-120,date:todayKey(),accountId:'',note:''},{id:uid(),name:'freelance income',category:'income',amount:2500,date:todayKey(),accountId:'',note:''}],
 accounts:[{id:uid(),name:'cash',amount:0,type:'cash'},{id:uid(),name:'saving',amount:0,type:'saving'},{id:uid(),name:'investment',amount:0,type:'investment'}],
 categories:[{id:uid(),name:'food',limit:5000},{id:uid(),name:'transportation',limit:2500},{id:uid(),name:'personal care',limit:1500},{id:uid(),name:'entertainment',limit:1500},{id:uid(),name:'education',limit:2500}],
 dailyLimit:750,
 recipes:[
  {id:uid(),name:'overnight berry oats',emoji:'🫐',time:'10–15 mins',category:'breakfast',uses:3,ingredients:['oats','almonds','blueberries']},
  {id:uid(),name:'lemon butter pasta',emoji:'🍝',time:'10–15 mins',category:'main',uses:2,ingredients:['lemon','cream','mint']},
  {id:uid(),name:'vegan cashew curry',emoji:'🍛',time:'30–60 mins',category:'main',uses:1,ingredients:['cashews','onion','garlic']},
  {id:uid(),name:'steamed veggies',emoji:'🥦',time:'10 mins',category:'side',uses:2,ingredients:['carrot','broccoli']},
  {id:uid(),name:'chicken bowl',emoji:'🍗',time:'20 mins',category:'main',uses:2,ingredients:['chicken','carrot','rice']},
  {id:uid(),name:'healthy granola',emoji:'🥣',time:'15 mins',category:'snack',uses:1,ingredients:['oats','almonds','seeds']}
 ],
 meals:{}, grocery:[{id:uid(),name:'milk',done:false},{id:uid(),name:'eggs',done:false},{id:uid(),name:'oats',done:false},{id:uid(),name:'lemon',done:false},{id:uid(),name:'chicken',done:false},{id:uid(),name:'cashews',done:false}],
 ingredients:['oats','almonds','blueberries','lemon','cream','mint','chicken','carrot','onion','garlic','cashews','olive oil'],
 goals:[{id:uid(),area:'Korean',title:'become conversational',progress:38},{id:uid(),area:'Academics',title:'master core pharmacy subjects',progress:54},{id:uid(),area:'Body',title:'build a stronger body',progress:44},{id:uid(),area:'Finance',title:'build a saving + investing system',progress:27},{id:uid(),area:'Self growth',title:'become the person I respect',progress:32}],
 projects:[{id:uid(),name:'Korean speaking',goalId:'',progress:36},{id:uid(),name:'Semester pharmacy prep',goalId:'',progress:52},{id:uid(),name:'Personal finance system',goalId:'',progress:22}],
 priorities:['Korean speaking practice','pharmacy mechanisms','bio practice test','workout 3×','read 30 pages'],
 journal:[], brain:'', checkins:[]
};

function migrate(s){
  if(!s) return seed;
  // v1.2 arrays → v1.3 objects
  s.tasks=(s.tasks||[]).map(t=>({...t,projectId:t.projectId||'',goalId:t.goalId||'',repeat:t.repeat||'none',subtasks:t.subtasks||[],created:t.created||Date.now()}));
  s.habits=(s.habits||[]).map(h=>({id:h.id||uid(),name:h.name||'habit',icon:h.icon||'✦',frequency:h.frequency||'daily',target:h.target||1,days:h.days||{}}));
  s.studyTasks=s.studyTasks||[]; s.studyMinutes=s.studyMinutes||0; s.studyLog=s.studyLog||{}; s.subjects=(s.subjects||[]).map(x=>Array.isArray(x)?{id:uid(),name:x[0],progress:x[1]}:x); s.notes=s.notes||[]; s.studyBlocks=s.studyBlocks||[];
  s.routines=(s.routines||[]).map(r=>Array.isArray(r)?{id:uid(),name:r[0],icon:r[1]||'✦',frequency:r[2]||'daily',target:1}:r); s.routineLog=s.routineLog||{}; s.waterLog=s.waterLog||{}; s.waterGoal=s.waterGoal||2; s.sleepLogs=s.sleepLogs||{}; s.sleepGoal=s.sleepGoal||8;
  s.entries=(s.entries||[]).map(e=>({...e,category:e.category||e.cat||'other',accountId:e.accountId||'',note:e.note||''})); s.accounts=(s.accounts||[]).map(a=>({...a,id:a.id||uid(),type:a.type||'cash'})); s.categories=(s.categories||[]).map(c=>Array.isArray(c)?{id:uid(),name:c[0],limit:c[1]}:c);
  s.recipes=(s.recipes||[]).map(r=>Array.isArray(r)?{id:uid(),name:r[0],emoji:r[1]||'🍽',time:r[2]||'20 mins',category:r[3]||'main',uses:r[4]||0,ingredients:[]}:r); s.grocery=(s.grocery||[]).map(g=>Array.isArray(g)?{id:uid(),name:g[0],done:!!g[1]}:g); s.ingredients=s.ingredients||[]; s.meals=s.meals||{};
  s.goals=(s.goals||[]).map(g=>Array.isArray(g)?{id:uid(),area:g[0],title:g[1],progress:g[2]||0}:g); s.automations=s.automations||[]; s.automationLog=s.automationLog||{}; s.projects=(s.projects||[]).map(p=>({...p,id:p.id||uid(),goalId:p.goalId||''})); s.priorities=s.priorities||[]; s.journal=s.journal||[]; s.brain=s.brain||''; s.checkins=s.checkins||[];
  return s;
}
let state=migrate(JSON.parse(localStorage.getItem(KEY)||'null'));
function save(){localStorage.setItem(KEY,JSON.stringify(state)); render(); queueCloudSync(); runAutomations();}
function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
function nav(page){$$('.page').forEach(x=>x.classList.toggle('active-page',x.id===page));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const label=page==='home'?'Home':document.querySelector(`[data-page="${page}"] span`)?.textContent||page;$('#pageTitle').textContent=label;window.scrollTo({top:0,behavior:'smooth'});$('#sidebar')?.classList.remove('open');}

function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open');setTimeout(()=>$('#modal input, #modal textarea, #modal select')?.focus(),30)}
function closeModal(){$('#modal').classList.remove('open');$('#modalBody').innerHTML=''}
function field(label,name,value='',type='text',extra=''){return `<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function selectField(label,name,options,value=''){return `<label>${esc(label)}<select name="${esc(name)}">${options.map(o=>`<option value="${esc(o[0])}" ${o[0]===value?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`}
function formModal(title, fields, onSave){openModal(`<span class="eyebrow">ELIF OS</span><h2>${esc(title)}</h2><form id="osForm"><div class="form-grid">${fields.join('')}</div><button class="primary full" type="submit">save</button></form>`);$('#osForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);const v=Object.fromEntries(fd.entries());onSave(v);closeModal();}}

function renderTasks(){
 const now=todayKey(), all=state.tasks, q=($('#taskSearch')?.value||'').toLowerCase();
 $('#taskTodayStat').textContent=all.filter(t=>t.date===now&&!t.done).length;
 $('#taskOverdueStat').textContent=all.filter(t=>t.date<now&&!t.done).length;
 $('#taskCompletionStat').textContent=(all.length?Math.round(all.filter(t=>t.done).length/all.length*100):0)+'%';
 $('#todayTasks').innerHTML=all.filter(t=>t.date===now&&!t.done).slice(0,5).map(t=>`<label><input type="checkbox" data-action="toggle-task" data-id="${t.id}"><span>${esc(t.title)}</span><em>${esc(t.priority)}</em></label>`).join('')||'<div class="empty">nothing urgent. make something meaningful.</div>';
 let filter=window.taskFilter||'today', arr=all.filter(t=>t.title.toLowerCase().includes(q));
 if(filter==='today')arr=arr.filter(t=>t.date===now&&!t.done); else if(filter==='next3')arr=arr.filter(t=>t.date>=now&&t.date<=addDays(now,3)&&!t.done); else if(filter==='next7')arr=arr.filter(t=>t.date>=now&&t.date<=addDays(now,7)&&!t.done); else if(filter==='completed')arr=arr.filter(t=>t.done);
 const sort=$('#taskSort')?.value||'date'; arr.sort((a,b)=>sort==='priority'?({high:0,medium:1,low:2}[a.priority]-({high:0,medium:1,low:2}[b.priority])):sort==='created'?b.created-a.created:a.date.localeCompare(b.date));
 $('#allTasks').innerHTML=arr.map(t=>{const subs=t.subtasks||[], subDone=subs.filter(s=>s.done).length; const project=state.projects.find(p=>p.id===t.projectId);return `<div class="task-row ${t.done?'done':''}"><input type="checkbox" data-action="toggle-task" data-id="${t.id}" ${t.done?'checked':''}><div class="task-main"><b>${esc(t.title)}</b><small>${fmtDate(t.date)} · ${esc(project?.name||'general')}${t.repeat&&t.repeat!=='none'?' · ↻ '+esc(t.repeat):''}${subs.length?` · ${subDone}/${subs.length} steps`:''}</small></div><span class="priority ${t.priority}">${esc(t.priority)}</span><button class="row-icon" data-action="edit-task" data-id="${t.id}">✎</button><button class="row-icon" data-action="delete-task" data-id="${t.id}">×</button></div>`}).join('')||'<div class="empty">no tasks in this view.</div>';
}
function taskForm(t){
 const projectOpts=[['','General'],...state.projects.map(p=>[p.id,p.name])], goalOpts=[['','None'],...state.goals.map(g=>[g.id,`${g.area} · ${g.title}`])];
 const fields=[field('name','title',t?.title||''),field('due','date',t?.date||todayKey(),'date'),selectField('priority','priority',[['low','low'],['medium','medium'],['high','high']],t?.priority||'medium'),selectField('project','projectId',projectOpts,t?.projectId||''),selectField('goal','goalId',goalOpts,t?.goalId||''),selectField('repeat','repeat',[['none','none'],['daily','daily'],['weekly','weekly'],['monthly','monthly']],t?.repeat||'none'),field('subtasks','subtasks',t?.subtasks?.map(x=>x.title).join('\n')||'','text','placeholder="one step per line"')];
 formModal(t?'edit task':'new task',fields,v=>{const subs=String(v.subtasks||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean).map((title,i)=>({id:t?.subtasks?.[i]?.id||uid(),title,done:t?.subtasks?.[i]?.done||false}));const data={title:v.title.trim()||'untitled',date:v.date||todayKey(),priority:v.priority,projectId:v.projectId,goalId:v.goalId,repeat:v.repeat,subtasks:subs};if(t)Object.assign(t,data);else state.tasks.unshift({id:uid(),...data,done:false,created:Date.now()});save();toast(t?'task updated':'task added ♡')});
}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.done=!t.done;if(t.done&&t.repeat!=='none'){const next=t.repeat==='daily'?addDays(t.date,1):t.repeat==='weekly'?addDays(t.date,7):addDays(t.date,30);state.tasks.push({...t,id:uid(),date:next,done:false,created:Date.now(),subtasks:(t.subtasks||[]).map(s=>({...s,id:uid(),done:false}))});}save();toast(t.done?'task completed ♡':'task reopened')}
function renderHabits(){
 const days=Array.from({length:7},(_,i)=>addDays(todayKey(),i-6));let total=0,done=0;
 $('#habitGrid').innerHTML=state.habits.map(h=>{const checks=days.map(d=>{const on=!!h.days[d];total++;if(on)done++;return `<button class="habit-day ${on?'on':''}" data-action="toggle-habit" data-id="${h.id}" data-date="${d}" title="${fmtDate(d)}">${on?'✓':''}</button>`}).join('');return `<div class="habit-row"><div class="habit-name"><span>${esc(h.icon)}</span><b>${esc(h.name)}</b><small>${esc(h.frequency)} · ${calcStreak(h)} day streak</small></div><div class="habit-week"><small>7d</small>${checks}</div><button class="row-icon" data-action="edit-habit" data-id="${h.id}">✎</button><button class="row-icon" data-action="delete-habit" data-id="${h.id}">×</button></div>`}).join('')||'<div class="empty">add your first habit.</div>';
 const todayDone=state.habits.filter(h=>h.days[todayKey()]).length; $('#habitToday').textContent=`${todayDone} / ${state.habits.length}`; $('#habitPct').textContent=(total?Math.round(done/total*100):0)+'%'; $('#bestStreak').textContent=Math.max(0,...state.habits.map(calcBestStreak))+' days';
 const px=[];for(let i=34;i>=0;i--){const d=addDays(todayKey(),-i),rate=state.habits.length?state.habits.filter(h=>h.days[d]).length/state.habits.length:0;px.push(`<span class="pixel p${Math.ceil(rate*4)}" title="${fmtDate(d)} · ${Math.round(rate*100)}%"></span>`)}$('#monthPixels').innerHTML=px.join('');
 $('#habitHistory').innerHTML=days.map(d=>`<div><b>${new Intl.DateTimeFormat('en',{weekday:'short'}).format(new Date(d+'T12:00:00'))}</b><span>${state.habits.filter(h=>h.days[d]).length}/${state.habits.length}</span></div>`).join('');
}
function calcStreak(h){let n=0,d=todayKey();while(h.days[d]){n++;d=addDays(d,-1)}return n}
function calcBestStreak(h){let best=0,run=0;for(let i=60;i>=0;i--){const d=addDays(todayKey(),-i);if(h.days[d]){run++;best=Math.max(best,run)}else run=0}return best}
function habitForm(h){formModal(h?'edit habit':'new habit',[field('name','name',h?.name||''),field('icon','icon',h?.icon||'✦'),selectField('frequency','frequency',[['daily','daily'],['3x week','3x week'],['weekly','weekly'],['monthly','monthly']],h?.frequency||'daily')],v=>{if(h)Object.assign(h,{name:v.name.trim()||'habit',icon:v.icon||'✦',frequency:v.frequency});else state.habits.push({id:uid(),name:v.name.trim()||'habit',icon:v.icon||'✦',frequency:v.frequency,target:v.frequency==='3x week'?3:1,days:{}});save();toast(h?'habit updated':'habit added ♡')})}
function toggleHabit(id,date){const h=state.habits.find(x=>x.id===id);if(!h)return;h.days[date]=!h.days[date];save();}

function renderStudy(){
 $('#studyTasks').innerHTML=state.studyTasks.map(t=>`<div class="task-row ${t.done?'done':''}"><input type="checkbox" data-action="toggle-study" data-id="${t.id}" ${t.done?'checked':''}><div class="task-main"><b>${esc(t.title)}</b><small>${esc(t.subject||'General')}</small></div><button class="row-icon" data-action="delete-study" data-id="${t.id}">×</button></div>`).join('')||'<div class="empty">nothing in study queue.</div>';
 $('#subjectGrid').innerHTML=state.subjects.map(s=>`<div class="subject"><div><b>${esc(s.name)}</b><span>${s.progress}%</span></div><div class="progress"><i style="width:${s.progress}%"></i></div><div><button data-action="subject-step" data-id="${s.id}">+5%</button><small>weekly mastery</small></div></div>`).join('');
 $('#notes').innerHTML=state.notes.map(n=>`<div class="note-row"><div><b>${esc(n.title)}</b><small>${esc(n.subject)} · review ${fmtDate(n.due)}</small></div><button class="row-icon" data-action="delete-note" data-id="${n.id}">×</button></div>`).join('')||'<div class="empty">add a revision note.</div>';
 const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];$('#timetable').innerHTML=days.map((d,i)=>{const blocks=state.studyBlocks.filter(b=>b.day===i);return `<div class="time-day"><b>${d}</b><button data-action="add-block" data-day="${i}">+ block</button>${blocks.map(b=>`<span>${esc(b.time)} · ${esc(b.title)} <button class="row-icon" data-action="delete-block" data-id="${b.id}">×</button></span>`).join('')||'<span class="muted">no block</span>'}</div>`}).join('');
 $('#studyTotal').textContent=(state.studyLog[todayKey()]||0)+'m';
}
function studyTaskForm(){formModal('new study task',[field('task','title',''),selectField('subject','subject',[['Pharmacology','Pharmacology'],['Biochemistry','Biochemistry'],['Korean','Korean'],['Anatomy','Anatomy'],['Finance','Finance'],['General','General']],'General')],v=>{state.studyTasks.push({id:uid(),title:v.title.trim()||'study task',subject:v.subject,done:false});save();toast('study task added')})}
function noteForm(){formModal('new revision note',[field('title','title',''),field('subject','subject','General'),field('review date','due',todayKey(),'date'),selectField('interval','push',[['day 1','day 1'],['day 3','day 3'],['day 7','day 7'],['day 14','day 14']], 'day 1')],v=>{state.notes.unshift({id:uid(),title:v.title.trim()||'note',subject:v.subject||'General',due:v.due||todayKey(),push:v.push});save();toast('revision note added')})}
function blockForm(day){formModal('new study block',[field('time','time','09:00','time'),field('activity','title','deep work')],v=>{state.studyBlocks.push({id:uid(),day:Number(day),time:v.time,title:v.title.trim()||'study'});save();toast('study block added')})}

let timer=1500, interval=null, focusDuration=25;
function timerPaint(){const s=Math.max(0,timer),txt=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;['#timer','#homeTimer'].forEach(id=>{if($(id))$(id).textContent=txt})}
function resetTimer(){clearInterval(interval);interval=null;timer=focusDuration*60;timerPaint()}
function startFocus(){if(interval)return;toast('focus started');interval=setInterval(()=>{timer--;timerPaint();if(timer<=0){clearInterval(interval);interval=null;state.studyMinutes+=focusDuration;state.studyLog[todayKey()]=(state.studyLog[todayKey()]||0)+focusDuration;save();timer=focusDuration*60;timerPaint();toast('focus complete ♡')}},1000)}

function renderGlow(){const today=todayKey();$('#routineGrid').innerHTML=state.routines.map(r=>{const key=`${today}:${r.id}`,done=!!state.routineLog[key];return `<div class="routine ${done?'done':''}"><div class="routine-icon">${esc(r.icon)}</div><h3>${esc(r.name)}</h3><small>${esc(r.frequency)}</small><div class="progress"><i style="width:${done?100:0}%"></i></div><button class="routine-done" data-action="routine-done" data-id="${r.id}">${done?'done ♡':'complete today'}</button><button class="row-icon" data-action="edit-routine" data-id="${r.id}">✎</button><button class="row-icon" data-action="delete-routine" data-id="${r.id}">×</button></div>`}).join('');
 const water=state.waterLog[today]||0;$('#waterAmount').textContent=water.toFixed(2)+' L';$('#waterBar').style.width=Math.min(100,water/state.waterGoal*100)+'%';$('#waterGoalLabel').textContent=`goal ${state.waterGoal.toFixed(1)} L`;
 const sleep=state.sleepLogs[today]||{sleep:'00:00',wake:'08:00'};$('#sleepTime').value=sleep.sleep;$('#wakeTime').value=sleep.wake;paintSleep(sleep.sleep,sleep.wake);
 $('#glowLogs').innerHTML=state.glowLogs.map(x=>`<div class="log"><span>${esc(x.text)}</span><small>${esc(x.date)}</small></div>`).join('')||'<div class="empty">your first glow-up log starts here.</div>';
}
function paintSleep(a,b){if(!a||!b)return;let [h,m]=a.split(':').map(Number),[h2,m2]=b.split(':').map(Number),mins=h2*60+m2-(h*60+m);if(mins<0)mins+=1440;$('#sleepDuration').textContent=Math.floor(mins/60)+'h '+mins%60+'m'}
function routineForm(r){formModal(r?'edit routine':'new routine',[field('name','name',r?.name||''),field('icon','icon',r?.icon||'✦'),selectField('frequency','frequency',[['daily','daily'],['3x week','3x week'],['weekly','weekly'],['monthly','monthly']],r?.frequency||'daily')],v=>{if(r)Object.assign(r,{name:v.name.trim()||'routine',icon:v.icon||'✦',frequency:v.frequency});else state.routines.push({id:uid(),name:v.name.trim()||'routine',icon:v.icon||'✦',frequency:v.frequency,target:v.frequency==='3x week'?3:1});save();toast(r?'routine updated':'routine added ♡')})}
function saveSleep(){state.sleepLogs[todayKey()]={sleep:$('#sleepTime').value||'00:00',wake:$('#wakeTime').value||'08:00'};save();toast('sleep log saved')}

function renderFinance(){
 const income=state.entries.filter(e=>e.amount>0).reduce((a,e)=>a+Number(e.amount),0), expense=-state.entries.filter(e=>e.amount<0).reduce((a,e)=>a+Number(e.amount),0);$('#balance').textContent=money(income-expense);const spent=-state.entries.filter(e=>e.date===todayKey()&&e.amount<0).reduce((a,e)=>a+Number(e.amount),0);$('#dailyLimit').textContent=money(state.dailyLimit);$('#limitStatus').textContent=money(Math.max(0,state.dailyLimit-spent))+' left today';
 $('#entries').innerHTML=state.entries.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20).map(e=>`<div class="entry"><div><b>${esc(e.name)}</b><small>${fmtDate(e.date)} · ${esc(e.category)}</small></div><strong class="${e.amount<0?'negative':'positive'}">${e.amount<0?'−':'+'}${money(Math.abs(e.amount)).replace('₺','₺')}</strong><button class="row-icon" data-action="delete-entry" data-id="${e.id}">×</button></div>`).join('')||'<div class="empty">no entries yet.</div>';
 $('#accounts').innerHTML=state.accounts.map(a=>`<div class="account"><div><b>${esc(a.name)}</b><small>${esc(a.type)}</small></div><strong>${money(a.amount)}</strong><button class="row-icon" data-action="edit-account" data-id="${a.id}">✎</button></div>`).join('');
 $('#categories').innerHTML=state.categories.map(c=>{const spentCat=-state.entries.filter(e=>e.category===c.name&&e.amount<0).reduce((a,e)=>a+Number(e.amount),0);const pct=c.limit?Math.min(100,spentCat/c.limit*100):0;return `<div class="category"><div><b>${esc(c.name)}</b><span>${money(spentCat)} / ${money(c.limit)}</span></div><div class="progress"><i style="width:${pct}%"></i></div><button class="row-icon" data-action="edit-category" data-id="${c.id}">✎</button></div>`}).join('');
 renderMoneyChart();
}
function entryForm(kind){const cats=[...state.categories.map(c=>[c.name,c.name]),['income','income'],['other','other']];formModal(kind==='expense'?'log expense':'log income',[field('name','name',kind==='expense'?'coffee':'income'),field('amount','amount','0','number','step="1" min="0"'),field('date','date',todayKey(),'date'),selectField('category','category',cats,kind==='expense'?'food':'income'),selectField('account','accountId',[['','none'],...state.accounts.map(a=>[a.id,a.name])],'')],v=>{const amt=Math.abs(Number(v.amount)||0)*(kind==='expense'?-1:1);state.entries.unshift({id:uid(),name:v.name.trim()||kind,category:v.category,amount:amt,date:v.date||todayKey(),accountId:v.accountId||'',note:''});if(v.accountId){const a=state.accounts.find(x=>x.id===v.accountId);if(a)a.amount+=amt}save();toast(kind+' logged')})}
function accountForm(a){formModal(a?'edit account':'new account',[field('name','name',a?.name||''),field('balance','amount',a?.amount||0,'number'),selectField('type','type',[['cash','cash'],['saving','saving'],['investment','investment']],a?.type||'cash')],v=>{if(a){Object.assign(a,{name:v.name.trim()||'account',amount:Number(v.amount)||0,type:v.type})}else state.accounts.push({id:uid(),name:v.name.trim()||'account',amount:Number(v.amount)||0,type:v.type});save();toast(a?'account updated':'account added')})}
function categoryForm(c){formModal(c?'edit category':'new category',[field('name','name',c?.name||''),field('monthly limit','limit',c?.limit||0,'number')],v=>{if(c)Object.assign(c,{name:v.name.trim()||'category',limit:Number(v.limit)||0});else state.categories.push({id:uid(),name:v.name.trim()||'category',limit:Number(v.limit)||0});save();toast('category saved')})}
function renderMoneyChart(){const months=[];const now=new Date();for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),key=d.toISOString().slice(0,7);const inc=state.entries.filter(e=>e.date.startsWith(key)&&e.amount>0).reduce((a,e)=>a+Number(e.amount),0),exp=-state.entries.filter(e=>e.date.startsWith(key)&&e.amount<0).reduce((a,e)=>a+Number(e.amount),0);months.push({label:new Intl.DateTimeFormat('tr-TR',{month:'short'}).format(d),inc,exp})}const max=Math.max(1,...months.flatMap(x=>[x.inc,x.exp]));$('#moneyChart').innerHTML=months.map(m=>`<div class="bar-col"><div class="bars"><i style="height:${m.inc/max*100}%" title="income ${money(m.inc)}"></i><i style="height:${m.exp/max*100}%" title="expense ${money(m.exp)}"></i></div><small>${esc(m.label)}</small></div>`).join('')+`<div class="chart-legend"><span>income</span><span>expense</span></div>`}

function renderMeals(){
 const days=['mon','tue','wed','thu','fri','sat','sun'];$('#mealWeek').innerHTML=days.map(d=>{const m=state.meals[d]||{};return `<div class="meal-day"><div><b>${d}</b><button data-action="edit-meal" data-day="${d}">✎</button></div><p>breakfast<br><strong>${esc(m.breakfast||'free choice')}</strong></p><p>lunch<br><strong>${esc(m.lunch||'free choice')}</strong></p><p>dinner<br><strong>${esc(m.dinner||'free choice')}</strong></p></div>`}).join('');
 $('#recipeGrid').innerHTML=state.recipes.map(r=>{const missing=(r.ingredients||[]).filter(x=>!state.ingredients.map(i=>i.toLowerCase()).includes(x.toLowerCase())).length;return `<div class="recipe"><div class="recipe-img">${esc(r.emoji)}</div><b>${esc(r.name)}</b><span>${esc(r.category)} · ${esc(r.time)}</span><small>added ${r.uses||0} times · ${missing?missing+' missing':'ingredients ready'}</small><div><button class="soft-btn" data-action="recommend-recipe" data-id="${r.id}">+ this week</button><button class="row-icon" data-action="edit-recipe" data-id="${r.id}">✎</button><button class="row-icon" data-action="delete-recipe" data-id="${r.id}">×</button></div></div>`}).join('');
 $('#groceryList').innerHTML=state.grocery.map(g=>`<label class="grocery"><input type="checkbox" data-action="toggle-grocery" data-id="${g.id}" ${g.done?'checked':''}><span class="${g.done?'strike':''}">${esc(g.name)}</span><button class="row-icon" data-action="delete-grocery" data-id="${g.id}">×</button></label>`).join('')||'<div class="empty">grocery list is clear.</div>';
 $('#ingredients').innerHTML=state.ingredients.map((x,i)=>`<span class="ingredient">${esc(x)} <button data-action="remove-ingredient" data-index="${i}">×</button></span>`).join('')||'<div class="empty">add ingredients to build recommendations.</div>';
}
function recipeForm(r){formModal(r?'edit recipe':'new recipe',[field('name','name',r?.name||''),field('emoji','emoji',r?.emoji||'🍽'),field('time','time',r?.time||'20 mins'),field('category','category',r?.category||'main'),field('ingredients','ingredients',(r?.ingredients||[]).join(', '))],v=>{const data={name:v.name.trim()||'recipe',emoji:v.emoji||'🍽',time:v.time||'20 mins',category:v.category||'main',ingredients:v.ingredients.split(',').map(x=>x.trim()).filter(Boolean)};if(r)Object.assign(r,data);else state.recipes.unshift({id:uid(),...data,uses:0});save();toast(r?'recipe updated':'recipe added')})}
function mealForm(day){const m=state.meals[day]||{};formModal(`meal plan · ${day}`,[field('breakfast','breakfast',m.breakfast||''),field('lunch','lunch',m.lunch||''),field('dinner','dinner',m.dinner||'')],v=>{state.meals[day]={breakfast:v.breakfast,lunch:v.lunch,dinner:v.dinner};save();toast('meal plan updated')})}

function renderGoals(){
 $('#goalGrid').innerHTML=state.goals.map((g,i)=>{const linked=state.projects.filter(p=>p.goalId===g.id);const derived=linked.length?Math.round(linked.reduce((a,p)=>a+p.progress,0)/linked.length):g.progress;return `<div class="goal"><span>0${i+1} · ${esc(g.area)}</span><h2>${esc(g.title)}</h2><div class="progress"><i style="width:${derived}%"></i></div><div class="goal-bottom"><small>${derived}% · ${linked.length} linked projects</small><button class="soft-btn" data-action="goal-step" data-id="${g.id}">+ milestone</button><button class="row-icon" data-action="edit-goal" data-id="${g.id}">✎</button></div></div>`}).join('')||'<div class="empty">define your first future-self goal.</div>';
}
function goalForm(g){formModal(g?'edit goal':'new goal',[field('area','area',g?.area||''),field('goal','title',g?.title||''),field('progress','progress',g?.progress||0,'number','min="0" max="100"')],v=>{const data={area:v.area.trim()||'General',title:v.title.trim()||'future goal',progress:Math.max(0,Math.min(100,Number(v.progress)||0))};if(g)Object.assign(g,data);else state.goals.push({id:uid(),...data});save();toast('goal saved ✦')})}
function renderProjects(){
 $('#projectGrid').innerHTML=state.projects.map(p=>{const tasks=state.tasks.filter(t=>t.projectId===p.id),done=tasks.filter(t=>t.done).length;const derived=tasks.length?Math.round(done/tasks.length*100):p.progress;const goal=state.goals.find(g=>g.id===p.goalId);return `<div class="project"><div><span>${esc(goal?.area||'unlinked goal')}</span><h2>${esc(p.name)}</h2></div><strong>${derived}%</strong><div class="progress"><i style="width:${derived}%"></i></div><small>${done}/${tasks.length} linked tasks${tasks.length?' · auto progress':''}</small><div><button class="soft-btn" data-action="project-step" data-id="${p.id}">+ milestone</button><button class="row-icon" data-action="edit-project" data-id="${p.id}">✎</button><button class="row-icon" data-action="delete-project" data-id="${p.id}">×</button></div></div>`}).join('')||'<div class="empty">turn a goal into a finite project.</div>';
}
function projectForm(p){formModal(p?'edit project':'new project',[field('project name','name',p?.name||''),selectField('linked goal','goalId',[['','none'],...state.goals.map(g=>[g.id,`${g.area} · ${g.title}`])],p?.goalId||''),field('manual progress','progress',p?.progress||0,'number','min="0" max="100"')],v=>{const data={name:v.name.trim()||'project',goalId:v.goalId||'',progress:Math.max(0,Math.min(100,Number(v.progress)||0))};if(p)Object.assign(p,data);else state.projects.push({id:uid(),...data});save();toast('project saved')})}

function renderJournal(){$('#journalList').innerHTML=state.journal.map(j=>`<article class="journal-entry"><div><span>${esc(j.mood||'good')}</span><small>${esc(j.date)}</small></div><h3>${esc(j.title||'untitled')}</h3><p>${esc(j.body)}</p><button class="row-icon" data-action="delete-journal" data-id="${j.id}">×</button></article>`).join('')||'<div class="empty">your journal starts here.</div>'}
let journalMood='good';
function saveJournal(){const title=$('#journalTitle').value.trim(),body=$('#journalBody').value.trim();if(!title&&!body)return toast('write something first');state.journal.unshift({id:uid(),date:fmtDate(todayKey()),title,body,mood:journalMood});$('#journalTitle').value='';$('#journalBody').value='';save();toast('journal saved ♡')}

function renderDashboard(){
 const days=['sun','mon','tue','wed','thu','fri','sat'], imgs=['hobbies','money','study','korean','body','hobbies','korean'], caps=[['reset plan','slow down'],['focus study','no excuses'],['progress','small wins'],['don’t overthink','just do it'],['trust the process','keep going'],['almost there','keep going'],['rest','reflect']];$('#weekOverview').innerHTML=days.map((d,i)=>`<button class="week-card" data-action="week-day" data-day="${d}"><img src="assets/${imgs[i]}.jpeg"><b>${d}</b><p>${caps[i][0]}</p><small>${caps[i][1]}</small></button>`).join('');
 const d0=new Date(),year=d0.getFullYear(),month=d0.getMonth(),first=new Date(year,month,1),start=(first.getDay()+6)%7,daysIn=new Date(year,month+1,0).getDate();let cells='';for(let i=0;i<42;i++){const n=i-start+1;if(n<1||n>daysIn){cells+='<div class="month-cell muted"></div>';continue}const d=`${year}-${String(month+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,tasks=state.tasks.filter(t=>t.date===d&&!t.done).length;cells+=`<button class="month-cell" data-action="month-day" data-date="${d}"><small>${n}</small>${tasks?`<em>${tasks} task${tasks>1?'s':''}</em>`:''}</button>`}$('#monthOverview').innerHTML=`<div class="month-top"><b>${new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(d0)}</b><span>tasks + habits + study</span></div><div class="month-grid">${cells}</div>`;
 const all=state.tasks.length, td=state.tasks.filter(t=>t.done).length,pct=all?Math.round(td/all*100):0;$('#focusPct').textContent=pct+'%';$('#focusBar').style.width=pct+'%';$('#focusTasks').textContent=state.tasks.filter(t=>!t.done).length;$('#focusHabits').textContent=state.habits.filter(h=>!h.days[todayKey()]).length;$('#focusStudy').textContent=(state.studyLog[todayKey()]||0)+'m';$('#glanceHabits').textContent=`${state.habits.filter(h=>h.days[todayKey()]).length}/${state.habits.length}`;$('#glanceStudy').textContent=(state.studyLog[todayKey()]||0)+'m';$('#glanceWater').textContent=(state.waterLog[todayKey()]||0).toFixed(1)+' L';$('#glanceSpend').textContent=money(-state.entries.filter(e=>e.date===todayKey()&&e.amount<0).reduce((a,e)=>a+Number(e.amount),0));$('#weekScore').textContent=`${state.tasks.filter(t=>t.done).length} tasks done`;$('#monthScore').textContent=`${state.goals.filter(g=>g.progress>=50).length} goals ≥ 50%`;$('#prioritiesList').innerHTML=state.priorities.map((p,i)=>{const t=state.tasks.find(x=>x.title===p);return `<label><input type="checkbox" data-action="priority" data-index="${i}" ${t?.done?'checked':''}><span>${esc(p)}</span></label>`}).join('');
 $('#todayDate').textContent=new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long'}).format(new Date());
}
function checkinModal(){openModal(`<span class="eyebrow">DAILY CHECK-IN</span><h2>How are you actually doing?</h2><form id="checkinForm"><div class="form-grid">${selectField('mood','mood',[['calm','calm'],['good','good'],['focused','focused'],['tired','tired'],['overwhelmed','overwhelmed']],'good')}${field('energy 1–10','energy','7','number','min="1" max="10"')}${field('sleep hours','sleep',String(Math.round(getSleepDuration()/60)),'number','min="0" max="24"')}${field('one thing','note','','text','placeholder="what matters most today?"')}</div><button class="primary full" type="submit">save check-in</button></form>`);$('#checkinForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target).entries());state.checkins.unshift({id:uid(),date:todayKey(),...v});save();closeModal();toast('check-in saved ☀')}}
function getSleepDuration(){const x=state.sleepLogs[todayKey()]||{sleep:'00:00',wake:'08:00'};let [h,m]=x.sleep.split(':').map(Number),[h2,m2]=x.wake.split(':').map(Number),mins=h2*60+m2-(h*60+m);if(mins<0)mins+=1440;return mins}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='elif-os-backup.json';a.click();URL.revokeObjectURL(a.href);toast('backup exported')}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{state=migrate(JSON.parse(r.result));save();toast('backup imported ♡')}catch{toast('invalid backup')}};r.readAsText(file)}
function settingsModal(){openModal(`<span class="eyebrow">ELIF OS</span><h2>system controls</h2><p class="muted">Local-first with optional cloud sync. Export a backup anytime.</p><div class="quick-modal"><button id="syncSettingsBtn">☁ cloud sync</button><button id="exportBtn">export backup</button><button id="importBtn">import backup</button><button id="resetBtn">reset demo data</button></div><input type="file" id="importFile" accept="application/json" hidden><div id="syncStatus" class="sync-status"></div>`);$('#syncSettingsBtn').onclick=syncModal;$('#exportBtn').onclick=exportData;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>importData(e.target.files[0]);$('#resetBtn').onclick=()=>{if(confirm('Reset ELIF OS demo data?')){state=migrate(JSON.parse(JSON.stringify(seed)));save();closeModal();toast('demo data restored')}};renderSyncStatus()}
function quickMenu(){openModal(`<span class="eyebrow">QUICK ADD</span><h2>What are we adding?</h2><div class="quick-modal">${[['task','✓ task'],['habit','✿ habit'],['expense','₺ expense'],['income','₺ income'],['goal','✦ goal'],['project','◇ project'],['recipe','🍞 recipe'],['journal','♡ journal'],['routine','⌁ routine'],['grocery','🛒 grocery']].map(x=>`<button data-quick="${x[0]}">${x[1]}</button>`).join('')}</div>`);$$('[data-quick]').forEach(b=>b.onclick=()=>{closeModal();quickAction(b.dataset.quick)})}
function quickAction(type){({task:()=>taskForm(),habit:()=>habitForm(),expense:()=>entryForm('expense'),income:()=>entryForm('income'),goal:()=>goalForm(),project:()=>projectForm(),recipe:()=>recipeForm(),journal:()=>nav('journal'),routine:()=>routineForm(),grocery:()=>formModal('new grocery item',[field('item','name','')],v=>{state.grocery.push({id:uid(),name:v.name.trim()||'item',done:false});save();toast('grocery item added')})}[type]||(()=>{}))()}

function handleAction(a,el){const id=el.dataset.id;
 if(a==='toggle-task')toggleTask(id); else if(a==='delete-task'){state.tasks=state.tasks.filter(x=>x.id!==id);save();toast('task deleted')} else if(a==='edit-task')taskForm(state.tasks.find(x=>x.id===id));
 else if(a==='toggle-habit')toggleHabit(id,el.dataset.date); else if(a==='edit-habit')habitForm(state.habits.find(x=>x.id===id)); else if(a==='delete-habit'){state.habits=state.habits.filter(x=>x.id!==id);save();}
 else if(a==='toggle-study'){const t=state.studyTasks.find(x=>x.id===id);if(t)t.done=!t.done;save()} else if(a==='delete-study'){state.studyTasks=state.studyTasks.filter(x=>x.id!==id);save()}
 else if(a==='subject-step'){const s=state.subjects.find(x=>x.id===id);if(s)s.progress=Math.min(100,s.progress+5);save()}
 else if(a==='delete-note'){state.notes=state.notes.filter(x=>x.id!==id);save()} else if(a==='add-block')blockForm(el.dataset.day); else if(a==='delete-block'){state.studyBlocks=state.studyBlocks.filter(x=>x.id!==id);save()}
 else if(a==='routine-done'){const key=`${todayKey()}:${id}`;state.routineLog[key]=!state.routineLog[key];save()} else if(a==='edit-routine')routineForm(state.routines.find(x=>x.id===id)); else if(a==='delete-routine'){state.routines=state.routines.filter(x=>x.id!==id);save()}
 else if(a==='delete-entry'){state.entries=state.entries.filter(x=>x.id!==id);save()} else if(a==='edit-account')accountForm(state.accounts.find(x=>x.id===id));
 else if(a==='edit-category')categoryForm(state.categories.find(x=>x.id===id));
 else if(a==='recommend-recipe'){const r=state.recipes.find(x=>x.id===id);if(r)r.uses=(r.uses||0)+1;save();toast('recipe added to this week')}
 else if(a==='edit-recipe')recipeForm(state.recipes.find(x=>x.id===id)); else if(a==='delete-recipe'){state.recipes=state.recipes.filter(x=>x.id!==id);save()}
 else if(a==='toggle-grocery'){const g=state.grocery.find(x=>x.id===id);if(g)g.done=!g.done;save()} else if(a==='delete-grocery'){state.grocery=state.grocery.filter(x=>x.id!==id);save()}
 else if(a==='remove-ingredient'){state.ingredients.splice(Number(el.dataset.index),1);save()}
 else if(a==='goal-step'){const g=state.goals.find(x=>x.id===id);if(g)g.progress=Math.min(100,g.progress+5);save();toast('goal milestone +5%')}
 else if(a==='edit-goal')goalForm(state.goals.find(x=>x.id===id));
 else if(a==='project-step'){const p=state.projects.find(x=>x.id===id);if(p)p.progress=Math.min(100,p.progress+5);save();toast('project milestone +5%')} else if(a==='edit-project')projectForm(state.projects.find(x=>x.id===id)); else if(a==='delete-project'){state.projects=state.projects.filter(x=>x.id!==id);state.tasks.forEach(t=>{if(t.projectId===id)t.projectId=''});save()}
 else if(a==='delete-journal'){state.journal=state.journal.filter(x=>x.id!==id);save()}
 else if(a==='toggle-automation'){const x=state.automations.find(x=>x.id===id);if(x)x.enabled=el.checked;save()} else if(a==='edit-automation')automationForm(state.automations.find(x=>x.id===id)); else if(a==='delete-automation'){state.automations=state.automations.filter(x=>x.id!==id);save()}
 else if(a==='week-day'){window.taskFilter='all';$$('[data-task-filter]').forEach(x=>x.classList.toggle('active',x.dataset.taskFilter==='all'));nav('tasks');renderTasks();}
 else if(a==='month-day'){window.taskFilter='all';nav('tasks');$('#taskSearch').value='';renderTasks();toast(`${fmtDate(el.dataset.date)} selected`)}
 else if(a==='priority'){const p=state.priorities[Number(el.dataset.index)],t=state.tasks.find(x=>x.title===p);if(t)t.done=el.checked;else if(el.checked)state.tasks.push({id:uid(),title:p,date:todayKey(),priority:'medium',done:true,projectId:'',goalId:'',repeat:'none',subtasks:[],created:Date.now()});save()}
}

// Events
$$('.nav').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));
$('#mobileMenu')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.go)));
$('#topQuickAdd')?.addEventListener('click',quickMenu); $('#quickAdd')?.addEventListener('click',quickMenu);
$('#searchBtn')?.addEventListener('click',()=>{$('#searchOverlay').classList.add('open');$('#globalSearch').focus()});$('#openSearch')?.addEventListener('click',()=>$('#searchBtn').click());$('#searchClose')?.addEventListener('click',()=>$('#searchOverlay').classList.remove('open'));
$('#profileBtn')?.addEventListener('click',settingsModal);$('#openCloudSync')?.addEventListener('click',syncModal);$('#requestNotifications')?.addEventListener('click',async()=>{if('Notification' in window){const p=await Notification.requestPermission();toast(p==='granted'?'notifications enabled ♡':'notifications not enabled')}});$('#addAutomation')?.addEventListener('click',()=>automationForm());$('#openSettings')?.addEventListener('click',settingsModal);$('#checkinBtn')?.addEventListener('click',checkinModal);
$('#modalClose')?.addEventListener('click',closeModal);$('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
$('#addTask')?.addEventListener('click',()=>taskForm());$('#addHabit')?.addEventListener('click',()=>habitForm());$('#addStudy')?.addEventListener('click',studyTaskForm);$('#addNote')?.addEventListener('click',noteForm);$('#addBlock')?.addEventListener('click',()=>blockForm(0));$('#addRoutine')?.addEventListener('click',()=>routineForm());$('#logGlow')?.addEventListener('click',()=>{state.glowLogs.unshift({date:fmtDate(todayKey()),text:'self-care / glow-up logged'});save();toast('glow-up log added ♡')});
$$('[data-water]').forEach(b=>b.addEventListener('click',()=>{const d=todayKey();state.waterLog[d]=(state.waterLog[d]||0)+Number(b.dataset.water);save();toast('water logged 💧')}));$('#sleepTime')?.addEventListener('change',saveSleep);$('#wakeTime')?.addEventListener('change',saveSleep);
$('#addExpense')?.addEventListener('click',()=>entryForm('expense'));$('#addIncome')?.addEventListener('click',()=>entryForm('income'));$('#addAccount')?.addEventListener('click',()=>accountForm());$('#addCategory')?.addEventListener('click',()=>categoryForm());$('#addRecipe')?.addEventListener('click',()=>recipeForm());$('#addMeal')?.addEventListener('click',()=>mealForm('mon'));$('#addGrocery')?.addEventListener('click',()=>formModal('new grocery item',[field('item','name','')],v=>{state.grocery.push({id:uid(),name:v.name.trim()||'item',done:false});save();toast('grocery item added')}));$('#addIngredient')?.addEventListener('click',()=>formModal('new ingredient',[field('ingredient','name','')],v=>{state.ingredients.push(v.name.trim()||'ingredient');save();toast('ingredient added')}));$('#addProject')?.addEventListener('click',()=>projectForm());$('#addGoal')?.addEventListener('click',()=>goalForm());$('#addPriority')?.addEventListener('click',()=>formModal('new priority',[field('priority','name','')],v=>{state.priorities.push(v.name.trim()||'priority');save();toast('priority added')}));
$('#saveJournal')?.addEventListener('click',saveJournal);$$('#journalMood button').forEach(b=>b.addEventListener('click',()=>{journalMood=b.dataset.mood;$$('#journalMood button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));$('#saveBrain')?.addEventListener('click',()=>{state.brain=$('#brainDump').value;save();toast('brain dump saved')});
$('#startTimer')?.addEventListener('click',startFocus);$('#homeStartTimer')?.addEventListener('click',startFocus);$('#resetTimer')?.addEventListener('click',resetTimer);$('#homeResetTimer')?.addEventListener('click',resetTimer);$$('[data-focus]').forEach(b=>b.addEventListener('click',()=>{focusDuration=Number(b.dataset.focus);resetTimer();$$('[data-focus]').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
$('#refreshDashboard')?.addEventListener('click',()=>{render();toast('dashboard refreshed')});
$('#taskSearch')?.addEventListener('input',renderTasks);$('#taskSort')?.addEventListener('change',renderTasks);$$('[data-task-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-task-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.taskFilter=b.dataset.taskFilter;renderTasks()}));
$('#globalSearch')?.addEventListener('input',()=>{const q=$('#globalSearch').value.toLowerCase();const items=[...state.tasks.map(x=>({type:'task',name:x.title,page:'tasks'})),...state.goals.map(x=>({type:'goal',name:x.title,page:'goals'})),...state.projects.map(x=>({type:'project',name:x.name,page:'projects'})),...state.recipes.map(x=>({type:'recipe',name:x.name,page:'meals'})),...state.habits.map(x=>({type:'habit',name:x.name,page:'habits'})),...state.notes.map(x=>({type:'note',name:x.title,page:'study'}))].filter(x=>x.name.toLowerCase().includes(q));$('#searchResults').innerHTML=items.slice(0,15).map(x=>`<button class="search-result" data-search-page="${x.page}"><span>${esc(x.type)}</span><b>${esc(x.name)}</b></button>`).join('')||'<div class="empty">nothing found.</div>'});
$('#breakTask')?.addEventListener('click',()=>{const title=prompt('Task to break down:',state.tasks[0]?.title||'');if(!title)return;const steps=['Define the outcome','Gather what you need','Do the smallest first action','Complete the main work','Review and close the loop'];$('#breakdownResult').innerHTML=`<b>${esc(title)}</b><ol>${steps.map(x=>`<li>${x}</li>`).join('')}</ol>`});

document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){e.preventDefault();handleAction(a.dataset.action,a);return}const sp=e.target.closest('[data-search-page]');if(sp){nav(sp.dataset.searchPage);$('#searchOverlay').classList.remove('open')}});
$$('[data-action="edit-meal"]').forEach(()=>{}); // delegated below

document.addEventListener('click',e=>{const b=e.target.closest('[data-action="edit-meal"]');if(b){e.preventDefault();mealForm(b.dataset.day)}});



/* ---------- Cloud Sync + Automation Engine (v1.4) ---------- */
function syncConfig(){try{const saved=JSON.parse(localStorage.getItem(SYNC_KEY)||'{}');const defaults=window.ELIF_OS_CONFIG||{};return {url:saved.url||defaults.supabaseUrl||'',anonKey:saved.anonKey||defaults.supabasePublishableKey||''}}catch{return window.ELIF_OS_CONFIG?{url:window.ELIF_OS_CONFIG.supabaseUrl||'',anonKey:window.ELIF_OS_CONFIG.supabasePublishableKey||''}:{}}}
function syncSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function setSyncConfig(v){localStorage.setItem(SYNC_KEY,JSON.stringify(v))}
function setSyncSession(v){if(v)localStorage.setItem(SESSION_KEY,JSON.stringify(v));else localStorage.removeItem(SESSION_KEY)}
function supabaseHeaders(token){const c=syncConfig();return {'apikey':c.anonKey,'Authorization':'Bearer '+(token||c.anonKey),'Content-Type':'application/json','Prefer':'return=representation'}}
function validSupabase(){const c=syncConfig();return /^https:\/\/[^\s]+/.test(c.url||'') && (c.anonKey||'').length>20}
async function authRequest(path,body){const c=syncConfig();if(!validSupabase())throw new Error('Supabase URL and anon key are required');const r=await fetch(c.url.replace(/\/$/,'')+'/auth/v1/'+path,{method:'POST',headers:supabaseHeaders(),body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.msg||j.error_description||j.message||'Authentication failed');return j}
async function signUp(email,password){const j=await authRequest('signup',{email,password});if(j.access_token){setSyncSession(j);toast('cloud account created ♡');await cloudSyncNow()}else toast('account created — check your email if confirmation is enabled')}
async function signIn(email,password){const j=await authRequest('token?grant_type=password',{email,password});setSyncSession(j);toast('signed in ♡');await cloudSyncNow()}
function signOut(){setSyncSession(null);toast('signed out — local mode remains available');renderSyncStatus()}
async function fetchCloud(){const c=syncConfig(),s=syncSession();if(!s)throw new Error('Sign in first');const r=await fetch(c.url.replace(/\/$/,'')+'/rest/v1/elif_state?select=payload,updated_at&user_id=eq.'+encodeURIComponent(s.user.id),{headers:supabaseHeaders(s.access_token)});if(!r.ok)throw new Error('Could not read cloud data');const rows=await r.json();return rows[0]||null}
async function pushCloud(){const c=syncConfig(),s=syncSession();if(!s)throw new Error('Sign in first');const body={user_id:s.user.id,payload:state,updated_at:new Date().toISOString()};const r=await fetch(c.url.replace(/\/$/,'')+'/rest/v1/elif_state?on_conflict=user_id',{method:'POST',headers:{...supabaseHeaders(s.access_token),'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)});if(!r.ok)throw new Error('Could not upload cloud data')}
async function cloudSyncNow(){if(!validSupabase()){renderSyncStatus();return}const s=syncSession();if(!s){renderSyncStatus();return}try{const cloud=await fetchCloud();if(cloud?.payload){const localTime=Number(localStorage.getItem('elif-os-last-write')||0);const cloudTime=Date.parse(cloud.updated_at||0)||0;if(cloudTime>localTime){state=migrate(cloud.payload);localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem('elif-os-last-write',String(cloudTime));render();toast('cloud data downloaded ♡')}}await pushCloud();localStorage.setItem('elif-os-last-write',String(Date.now()));toast('synced across devices ♡');renderSyncStatus()}catch(e){console.warn(e);toast('sync failed: '+e.message);renderSyncStatus(e.message)}}
let syncTimer=null;
function queueCloudSync(){clearTimeout(syncTimer);if(!syncSession())return;syncTimer=setTimeout(()=>cloudSyncNow(),900)}
function renderSyncStatus(err=''){const el=$('#syncStatus');if(!el)return;const c=syncConfig(),s=syncSession();el.textContent=err?'sync error: '+err:s?(c.url?'cloud connected · '+(s.user?.email||'signed in'):'signed in'):c.url?'configured · sign in to sync':'local-only';el.className='sync-status '+(err?'error':s?'ok':'')}
function syncModal(){const c=syncConfig(),s=syncSession();openModal(`<span class="eyebrow">ELIF OS</span><h2>cloud sync</h2><p class="muted">Free Supabase sync keeps one ELIF OS database across iPhone, iPad and PC. Your password is sent directly to Supabase.</p><div class="form-grid"><label>Supabase project URL<input id="supabaseUrl" value="${esc(c.url||'')}" placeholder="https://xxxx.supabase.co"></label><label>Supabase anon/publishable key<input id="supabaseKey" value="${esc(c.anonKey||'')}" placeholder="eyJ..."></label><label>email<input id="syncEmail" type="email" value="${esc(s?.user?.email||'')}"></label><label>password<input id="syncPassword" type="password" placeholder="••••••••"></label></div><div class="sync-actions"><button class="soft-btn" id="saveSyncCfg">save connection</button><button class="primary" id="signInSync">sign in</button><button class="soft-btn" id="signUpSync">create account</button><button class="soft-btn" id="syncNow">sync now</button><button class="soft-btn" id="signOutSync">sign out</button></div><div id="syncStatus" class="sync-status"></div><p class="tiny muted">First-time setup also needs the SQL in <b>supabase-schema.sql</b> from the ZIP.</p>`);$('#saveSyncCfg').onclick=()=>{setSyncConfig({url:$('#supabaseUrl').value.trim(),anonKey:$('#supabaseKey').value.trim()});renderSyncStatus();toast('connection saved')};$('#signInSync').onclick=async()=>{try{setSyncConfig({url:$('#supabaseUrl').value.trim(),anonKey:$('#supabaseKey').value.trim()});await signIn($('#syncEmail').value.trim(),$('#syncPassword').value)}catch(e){toast(e.message)}};$('#signUpSync').onclick=async()=>{try{setSyncConfig({url:$('#supabaseUrl').value.trim(),anonKey:$('#supabaseKey').value.trim()});await signUp($('#syncEmail').value.trim(),$('#syncPassword').value)}catch(e){toast(e.message)}};$('#syncNow').onclick=cloudSyncNow;$('#signOutSync').onclick=signOut;renderSyncStatus()}
function automationDue(a,now){if(!a.enabled)return false;const last=state.automationLog[a.id]||'';const date=now.toISOString().slice(0,10);if(a.type==='daily-checkin'||a.type==='weekly-review'){if(last===date)return false;const h=now.getHours(),m=now.getMinutes();if(a.time && (h!==Number(a.time.split(':')[0])||m<Number(a.time.split(':')[1])||m>Number(a.time.split(':')[1])+1))return false;if(a.type==='weekly-review'&&now.getDay()!==1)return false;return true}if(a.type==='overdue'){return state.tasks.some(t=>!t.done&&t.date<date)&&last!==date}if(a.type==='review-due'){return state.notes.some(n=>n.due<=date)&&last!==date}return false}
function fireAutomation(a,now){state.automationLog[a.id]=now.toISOString().slice(0,10);let msg='';if(a.type==='daily-checkin')msg='Daily check-in: open ELIF OS and choose your top 3. ♡';if(a.type==='weekly-review')msg='Weekly review: look back, reset priorities, plan the week.';if(a.type==='overdue')msg='You have overdue tasks. Clear one before adding more.';if(a.type==='review-due')msg='Spaced-repetition reviews are due today.';if('Notification' in window&&Notification.permission==='granted')new Notification('ELIF OS',{body:msg});toast(msg);localStorage.setItem(KEY,JSON.stringify(state));render()}
function runAutomations(){const now=new Date();(state.automations||[]).forEach(a=>{if(automationDue(a,now))fireAutomation(a,now)});renderAutomationStatus?.()}
function automationForm(a){const types=[['daily-checkin','Daily check-in'],['weekly-review','Weekly review'],['overdue','Overdue task reminder'],['review-due','Study review reminder']];formModal(a?'edit automation':'new automation',[field('name','name',a?.name||''),selectField('type','type',types,a?.type||'daily-checkin'),field('time','time',a?.time||'20:00','time')],v=>{const obj={id:a?.id||uid(),name:v.name.trim()||'automation',type:v.type,time:v.time||'20:00',enabled:a?.enabled!==false};if(a)Object.assign(a,obj);else state.automations.push(obj);save();toast('automation saved')})}
function renderAutomationStatus(){const el=$('#automationList');if(!el)return;el.innerHTML=(state.automations||[]).map(a=>`<div class="automation-row"><div><b>${esc(a.name)}</b><small>${esc(a.type)} · ${esc(a.time||'event-based')}</small></div><label class="switch"><input type="checkbox" data-action="toggle-automation" data-id="${a.id}" ${a.enabled?'checked':''}><span></span></label><button class="row-icon" data-action="edit-automation" data-id="${a.id}">✎</button><button class="row-icon" data-action="delete-automation" data-id="${a.id}">×</button></div>`).join('')||'<div class="empty">no automations yet.</div>';renderSyncStatus()}

function render(){renderTasks();renderHabits();renderStudy();renderGlow();renderFinance();renderMeals();renderGoals();renderProjects();renderJournal();renderDashboard();renderAutomationStatus();if($('#brainDump'))$('#brainDump').value=state.brain||'';timerPaint();}
render();
runAutomations();
if(syncSession()) setTimeout(cloudSyncNow,1200);
setInterval(runAutomations,60000);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
