(()=>{
const KEY='elif-os-enhancements',get=()=>JSON.parse(localStorage.getItem(KEY)||'{"glow":{},"pomo":{}}'),put=s=>localStorage.setItem(KEY,JSON.stringify(s));
let timer,seconds=25*60,mode='focus',running=false;
const view=()=>document.querySelector('#view');
function fmt(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function study(){const s=get(),v=view();if(!v)return;v.dataset.page='study';v.innerHTML='<section><div class="viewhead"><div><h1>Study</h1><p>Focus deliberately, then rest deliberately.</p></div></div><div class="panel" style="max-width:680px;margin:auto;text-align:center"><span class="eyebrow" id="pomo-mode">FOCUS</span><strong id="pomo-time" style="display:block;font:72px DM Mono;margin:18px">25:00</strong><div class="quick"><button class="ghost" data-pomo="focus">25 min focus</button><button class="ghost" data-pomo="short">5 min break</button><button class="ghost" data-pomo="long">15 min break</button></div><div class="actions" style="justify-content:center"><button class="primary" data-pomo="start">start</button><button class="ghost" data-pomo="reset">reset</button></div><p class="muted">Completed focus sessions are saved locally.</p></div></section>';draw()}
function draw(){let t=document.querySelector('#pomo-time'),m=document.querySelector('#pomo-mode');if(t)t.textContent=fmt(seconds);if(m)m.textContent=mode==='focus'?'FOCUS':mode==='short'?'SHORT BREAK':'LONG BREAK'}
function glow(){const s=get(),g=s.glow||{},items=['AM cleanse + moisturize','SPF','PM cleanse','Treatment / serum','Moisturize','Hair care','Water goal'];const v=view();if(!v)return;v.dataset.page='glow';v.innerHTML='<section><div class="viewhead"><div><h1>Glow Up</h1><p>A small routine that makes care visible.</p></div></div><div class="data">'+items.map((x,i)=>'<button class="panel habit '+(g[i]?'on':'')+'" data-glow="'+i+'"><b>'+ (g[i]?'✓':'○')+'</b><h3>'+x+'</h3><small>'+ (g[i]?'done today':'tap to complete')+'</small></button>').join('')+'</div></section>'}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page==='study'||b.dataset.page==='glow'){e.preventDefault();e.stopImmediatePropagation();clearInterval(timer);b.dataset.page==='study'?study():glow();return}if(b.dataset.glow!==undefined){e.preventDefault();e.stopImmediatePropagation();const s=get();s.glow??={};s.glow[b.dataset.glow]=!s.glow[b.dataset.glow];put(s);glow();return}if(b.dataset.pomo){e.preventDefault();e.stopImmediatePropagation();const x=b.dataset.pomo;if(['focus','short','long'].includes(x)){mode=x;seconds=(x==='focus'?25:x==='short'?5:15)*60;running=false;clearInterval(timer);draw()}else if(x==='reset'){running=false;clearInterval(timer);seconds=(mode==='focus'?25:mode==='short'?5:15)*60;draw()}else if(x==='start'&&!running){running=true;timer=setInterval(()=>{if(--seconds<=0){clearInterval(timer);running=false;if(mode==='focus'){const s=get();s.pomo??={};s.pomo[new Date().toISOString().slice(0,10)]=(s.pomo[new Date().toISOString().slice(0,10)]||0)+25;put(s)}seconds=0}draw()},1000)} }},true);
})();
